<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-12-07 21:45

$extensionPath = t3lib_extMgm::extPath('sitemgr');
$extensionClassesPath = t3lib_extMgm::extPath('sitemgr') . 'Classes/';
return array(
	'tx_sitemgr_controller_extdirectdispatchercontroller' => $extensionClassesPath . 'Controller/ExtDirectDispatcherController.php',
	'tx_sitemgr_controller_extmgmupdatercontroller' => $extensionClassesPath . 'Controller/ExtMgmUpdaterController.php',
	'tx_sitemgr_controller_sitemanagercontroller' => $extensionClassesPath . 'Controller/SiteManagerController.php',
	'tx_sitemgr_controller_abstract_extmgmupdaterabstract' => $extensionClassesPath . 'Controller/Abstract/ExtMgmUpdaterAbstract.php',
	'tx_sitemgr_fe_contentpostproc' => $extensionClassesPath . 'Fe/ContentPostProc.php',
	'tx_sitemgr_modules_abstract_abstractcontroller' => $extensionClassesPath . 'Modules/Abstract/AbstractController.php',
	'tx_sitemgr_modules_beuser_beusercontroller' => $extensionClassesPath . 'Modules/BeUser/BeUserController.php',
	'tx_sitemgr_modules_customer_customercontroller' => $extensionClassesPath . 'Modules/Customer/CustomerController.php',
	'tx_sitemgr_modules_help_helpcontroller' => $extensionClassesPath . 'Modules/Help/HelpController.php',
	'tx_sitemgr_toolbaritems_customerselector_item' => $extensionClassesPath . 'ToolbarItems/CustomerSelector/Item.php',
	'tx_sitemgr_utilities_customermoduleutilities' => $extensionClassesPath . 'Utilities/CustomerModuleUtilities.php',
	'tx_sitemgr_utilities_customerutilities' => $extensionClassesPath . 'Utilities/CustomerUtilities.php',
	'tx_sitemgr_utilities_registry' => $extensionClassesPath . 'Utilities/Registry.php',
	'tx_sitemgr_viewhelper_be_doc_addcssfileviewhelper' => $extensionClassesPath . 'ViewHelper/Be/Doc/AddCssFileViewHelper.php',
	'tx_sitemgr_viewhelper_be_doc_addinlinelanguagelabelfileviewhelper' => $extensionClassesPath . 'ViewHelper/Be/Doc/AddInlineLanguageLabelFileViewHelper.php',
	'tx_sitemgr_viewhelper_be_doc_addinlinesettingarrayviewhelper' => $extensionClassesPath . 'ViewHelper/Be/Doc/AddInlineSettingArrayViewHelper.php',
	'tx_sitemgr_viewhelper_be_doc_addjsfileviewhelper' => $extensionClassesPath . 'ViewHelper/Be/Doc/AddJsFileViewHelper.php',
	'tx_sitemgr_viewhelper_be_doc_addjsfooterfileviewhelper' => $extensionClassesPath . 'ViewHelper/Be/Doc/AddJsFooterFileViewHelper.php',
);
?>